### ISSUE TITLE
Compile failure w/ GHC 7.10/7.8

### ISSUE THREAD

**Issue by hvr** [mrkkrp/forma#1]
Hi,

I get the following w/ GHC 7.10.3:

```
Configuring component lib from forma-0.1.0...
Warning: The package has a version range for a dependency on an internal library: forma >=0.1.0. This version range has no semantic meaning and can be removed.
Preprocessing library forma-0.1.0...

Web/Forma.hs:62:14: Unsupported extension: TypeApplications
```

this can be avoided by telling Cabal via `other-extensions: TypeApplications` that a compiler is required which supports the given extension (w/o enabling it).

**Comment by mrkkrp** [comment]
Yes, I state expliticely in the documentation that at least GHC 8 is required. Thanks for this tip about `other-extensions`, I'll apply that.
