### ISSUE TITLE
Converting FormResult to JSON

### ISSUE THREAD

**Issue by reygoch** [mrkkrp/forma#18]
So, I understood from the description that if I were to submit JSON like this :

```
{ username : "", password : "somepassword"}
```

and write a form parser, I'd be able to get something like this back if there was an error

```
{username: "can't be empty", password : null}
```

but I'm having trouble converting `FormResult` to `JSON`. It has `ToJSON` instance but when I try to use it I get the following error :

```
    * No instance for (ToJSONKey (FieldName CredentialsFields))
        arising from a use of `toJSON'
    * In the first argument of `encode', namely `(toJSON v)'
      In the `errBody' field of a record
      In the first argument of `throwError', namely
        `err400 {errBody = encode (toJSON v)}'
   |
41 |     go (ValidationFailed v) = throwError err400 {errBody = encode (toJSON v)}
   |                                                                    ^^^^^^^^
```

I've checked out the `ToJSONKey` class, but am unsure of how to implement it in this case.

I've also just tried to make "automatic" `ToJSONKey` instance like this :

```
instance ToJSONKey (FieldName CredentialsFields)
```

but than I get the following result when converting `FormResult` to JSON:

```
[["password","This field cannot be empty."],["username","This field cannot be empty."]]
```

which should actually be this :

```
{"password" : "This field cannot be empty.", "username" : "This field cannot be empty."}

**Comment by reygoch** [comment]
Ok, I've figured it out (I think), this is the required instance for this particular case:

type CredentialsFields = '["username", "password"]

```
import Web.Forma
import Data.Aeson
import Data.Aeson.Encoding ( text )
...
instance ToJSONKey (FieldName CredentialsFields) where
  toJSONKey = ToJSONKeyText f g
    where
      f = showFieldName
      g = text . showFieldName
```

**Comment by mrkkrp** [comment]
Can you share a more complete example?

**Comment by mrkkrp** [comment]
Closing an inactive.
