### ISSUE TITLE
co-maintainer

### ISSUE THREAD

**Issue by tzemanovic** [mrkkrp/forma#19]
Hey Mark,

I'd be happy to help as co-maintainer for this project as I'm already familiar with its API and your design decisions.

Cheers,
Tomas

**Comment by mrkkrp** [comment]
Thanks! I added you as a collaborator on GitHub, you should have received an invitation. I'm going to add you on Hackage so you can do revisions and new releases if necessary. What is your Hackage user name?

**Comment by tzemanovic** [comment]
`tzemanovic`, cheers!

**Comment by mrkkrp** [comment]
It's done, then!
