### ISSUE TITLE
Link the introductory post in README

### ISSUE THREAD

**Issue by k-bx** [mrkkrp/forma#21]
I'm reading through https://markkarpov.com/post/putting-together-a-form-validation-library.html and it's very well put, I would recommend linking it as a first thing in the README. What do you think?

**Comment by mrkkrp** [comment]
It’s not linked right now because the post describes an older version of the library and it has involved quite a bit since then, so I thought it would be confusing.

**Comment by k-bx** [comment]
I see, thanks!
