### ISSUE TITLE
Dynamic list of fields

### ISSUE THREAD

**Issue by k-bx** [mrkkrp/forma#22]
I'd like to hear your opinion out on a problem I'm having. My form has a dynamic list of "click trackers" fields, you can add up to three of them. What would be your idea on solving this kind of thing?

"Hacky" way to solve this is to list the fields `click_trackers_0`, `click_trackers_1`, `click_trackers_2` and render their errors under these names, but maybe you have a better idea.

Thanks!

**Comment by tzemanovic** [comment]
Could it work to parse them into a list and in validation create a list of the same length in the same order with Maybes for errors?

**Comment by k-bx** [comment]
I guess that's an alternative way to go as well. The problem here is that currently my front-end code just knows that the response for errors is key-value dict where key is `String` with field name and val is a `String` with error message. Now it'd have to dynamically see which field has which type. I think I'd prefer the dynamic field name approach here and keep the error structure flat, at least that's my current intuition.
