### ISSUE TITLE
Dependent fields

### ISSUE THREAD

**Issue by k-bx** [mrkkrp/forma#23]
My form has a boolean checkbox, which, when checked, should render and validate a second part of the form. Am I understanding correctly that this isn't supported via forma currently and I'd need to move all the validation of that second checkbox-enabled part of the form into some post-processing?

Thank you!

**Comment by tzemanovic** [comment]
Hi, you can do that with the [withCheck](https://hackage.haskell.org/package/forma-1.1.0/docs/Web-Forma.html#v:withCheck) function.

**Comment by k-bx** [comment]
Yeah, should probably work.
