### ISSUE TITLE
Validation failures use an incomplete path

### ISSUE THREAD

**Issue by gelisam** [mrkkrp/forma#24]
The tests for `subParser` say that if the field `username.password.remember_me` is missing or fails to parse, that fact should be reported at the path `username.password.remember_me`, but if that same field fails its validation, that fact [should instead be reported at the path `username`](https://github.com/mrkkrp/forma/blob/3813f201d0a2b6a5bc9a948c73043dc1abaabecd/tests/Main.hs#L176), not `username.password.remember_me`? That doesn't seem right to me.

**Comment by tzemanovic** [comment]
For this parser, the validation is `withCheck #username notEmpty`, so when it fails, it is correct to report it at `username` path.

That being said, this parser is a bit strange looking, you'd probably never use it like this as the value under the path `username.password.remember_me` ends up in the `username` field after parsing.

**Comment by mrkkrp** [comment]
Yeah, this example is completely artificial and is there just to test some cases. If we moved `withCheck` thing closer to actual `remember_me` field, then both cases would report the same path.

**Comment by gelisam** [comment]
Ah, I see. So if I use this `FormParser` instead:

    let p :: Monad m => FormParser LoginFields Text m Text
        p = subParser #username
          $ subParser #password
          $ withCheck #remember_me notEmpty
          $ field' #remember_me

or perhaps

    let p :: Monad m => FormParser LoginFields Text m Text
        p = subParser #username
          $ subParser #password
          $ field #remember_me notEmpty

then I should get the path `username.password.remember_me`? Unfortunately, I instead get `username.password` in both cases :(

**Comment by mrkkrp** [comment]
I'll take another look later today.

**Comment by mrkkrp** [comment]
Actually just from looking at the code it looks there is a bug. The check should wrap `value` primitive directly and then the whole thing should be wrapped in `subParser` then you'll get correct paths I think:

https://github.com/mrkkrp/forma/blob/master/Web/Forma.hs#L315

Easy to fix though.

**Comment by mrkkrp** [comment]
@gelisam Looks like a bug. Please take a look at #25 and see if it fixes the issue for you.

**Comment by gelisam** [comment]
> Please take a look at #25 and see if it fixes the issue for you.

It does, thanks!

**Comment by mrkkrp** [comment]
I have released version 1.1.1 with the fix, thanks for reporting this!
