### ISSUE TITLE
Provide explicit Proxy versions

### ISSUE THREAD

**Issue by sboosali** [mrkkrp/forma#5]
i.e. 

```
field = fieldWith Nothing

fieldWith proxy = ...

```
1) GHCJS is still at 8.0, which doesn't have TypeApplications, and which is used by a relevant percentage of webapps, many of which use form validations.

2) explicit proxy versions are useful anyways, for writing custom wrappers.

**Comment by mrkkrp** [comment]
GHC 8.0 has `TypeApplications` and I see the official readme says:

> (GHC 8 support is in the ghc-8.0 branch).

That said, I'm not very familiar with GHCJS, so I won't pretend I know if it supports `TypeApplications` or not :)

> explicit proxy versions are useful anyways, for writing custom wrappers.

You could use `ScopedTypeVariables`.

**Comment by mrkkrp** [comment]
Wontfix, probably.

**Comment by mrkkrp** [comment]
FYI, version 1.0.0 will use overloaded labels instead which is virtually the same as what you ask here. See #14.
